## In press

Berks, J., & Williams, M. N. (in press). Does conflictual dialogue improve a story? *Europe's Journal of Psychology*.

Paing, L. A., O'Keefe, K. M. P., McMurtrie, B. L., & Williams, M. N. (in press). Does answering survey questions about mental health cause distress? *Meta-Psychology*. Postprint: <https://doi.org/10.31234/osf.io/pqnvx>

Feather, G., & Williams, M. N. (in press). A psychometric evaluation of the Climate Change Anxiety Scale. *New Zealand Journal of Psychology*. Postprint: <https://doi.org/10.31234/osf.io/uzf7j>

## Published articles

Marques, M. D., Williams, M. N., Clarke, E. J. R., Fida, N., Heffernan, J., Hill, S. R., Kerr, J. R., Ling, M., Parkinson, C., Thermos, M., & Tier, J. (2026). Testing the socio-functional model: Does precarity cause conspiracy belief? *British Journal of Social Psychology, 65*(1). <https://doi.org/10.1111/bjso.70037>

McMurtrie, B., Williams, M., Hebden, R., Roemer, A., & Philipp, M. (2025). Political polarization and wellbeing: Investigating potential intrapersonal harm from affective polarization. *International Review of Social Psychology, 38*(1)*.* <https://doi.org/10.5334/irsp.1052>

Henry, N. I. N., Pedersen, M., Williams, M., N., & Donkin, L. (2025). Quantifying opponent process dynamics in pornography use and masturbation: An exploratory ecological momentary assessment study. *Archives of Sexual Behavior*. Advance online publication. <https://doi.org/10.1007/s10508-025-03287-z>

Clarke, E., Eckerle, F., Kerr, J., Hill, S., Ling, M., Marques, M., & Williams, M. N. (2025). Extremism at the centre: Uncovering political diversity amongst midpoint responders on the left-right self-placement item. *Political Psychology*. Advance online publication. <https://doi.org/10.1111/pops.70082>

Henry, N. I. N., Pedersen, M., Williams, M. N., Martin, J. L. B., & Donkin, L. (2025). A hormetic approach to the value-loading problem: Preventing the paperclip apocalypse? *SN Computer Science, 6*. <https://doi.org/10.1007/s42979-025-04369-4>

Doyle, E. E. H., Thompson, J., Hill, S. R., Williams, M., Paton, D., Harrison, S. E., Bostrom, A., & Becker, J. S. (2025). Communicating natural hazards science advice: Understanding scientists’, decision-makers’, and the public’s perceptions of the scientific process. *International Journal of Disaster Risk Reduction*, *128*, 105731. <https://doi.org/10.1016/j.ijdrr.2025.105731>

Fox, N. D., Williams, M. N., & Hill, S. R. (2025). Do stress, depression, and anxiety lead to beliefs in conspiracy theories? *Clinical Psychological Science*. Advance online publication. <https://doi.org/10.1177/21677026251370092>

Faulkner, J. W., Snell, D., Theadom, A., Siegert, R. J., Nielsen, K., & Williams, M. N. (2025). Identifying the bridges between post concussion symptoms and psychological distress in mild traumatic brain injury using network analysis. *The Journal of Head Trauma Rehabilitation*. <https://doi.org/10.1097/HTR.0000000000001104>

Neville, C. M., & Williams, M. N. (2025). Does truth pay? Investigating the effectiveness of the Bayesian truth serum with an interim payment: A registered report. *Advances in Methods and Practices in Psychological Science, 8*(3). <https://doi.org/10.1177/25152459251343043>

Henry, N. I. N., Pedersen, M., Williams, M. N., Martin, J. L. B., & Donkin, L. (2025). Reducing echo chamber effects: An allostatic regulator for recommendation algorithms. *Journal of Psychology and AI, 1*(1). <https://doi.org/10.1080/29974100.2025.2517191>

Williams, M. N., Marques, M. D., Kerr, J. R., Hill, S. R., Ling, M., & Clarke, E. J. R. (2025). Does developing a belief in one conspiracy theory lead a person to be more likely to believe in others? *European Journal of Social Psychology, 55*(4), 554-564. <https://doi.org/10.1002/ejsp.3153>

Faulkner, J., Prouty, D., Devlin, L., Appleton, D., Roche, M., Below, K., Moffat, J., Snell, D., Williams, M. N., Barker-Collo, S., & Theadom, A. (2025). Acceptance and commitment therapy for mild traumatic brain injury (ACTion-mTBI): A quasiexperimental feasibility study. *BMJ Open, 15*(2), e089727. <https://doi.org/10.1136/bmjopen-2024-089727>

Fox, N. D., & Williams, M. N. (2024). Do stress and anxiety lead to belief in conspiracy theories? \[version 2; peer review: 6 approved, 1 approved with reservations\]. *Routledge Open Research*. <https://doi.org/10.12688/routledgeopenres.17925.2>

McLean, T., Williams, M. N., & Stephens, C. (2025). How did the depression and anxiety levels of older New Zealanders change during the COVID-19 pandemic? *Psychology, Health & Medicine, 30*(2), 209-220. <https://doi.org/10.1080/13548506.2024.2407437>

Valdes, E. A., Liu, J. H., Williams, M. N., & Carr, S. C. (2025). A cross-cultural test of competing hypotheses about system justification using data from 42 nations. *Political Psychology, 46*(4), 822-846. <https://doi.org/10.1111/pops.13039>

Birchall, M., Drummond, A., & Williams, M. N. (2025). Antecedents of bullying victimisation in adolescents: a fresh look at Aotearoa New Zealand. *Kōtuitui: New Zealand Journal of Social Sciences Online, 20*(4), 528-541. <https://doi.org/10.1080/1177083X.2024.2385427>

Beaudry, J. L., Williams, M. N., Philipp, M. C., & Kothe, E. J. (2024). What do incoming university students believe about open science practices in psychology? *Teaching of Psychology, 51*(3), 269-276. <https://doi.org/10.1177/00986283221100276> Postprint: <https://doi.org/10.31234/osf.io/rq3zs>

McMurtrie, B. L., Philipp, M. C., Hebden, R. T., & Williams, M. N. (2024). Development and validation of the Affective Polarization Scale. *International Review of Social Psychology, 37*(1), 11. <https://doi.org/10.5334/irsp.926>

Doyle, E. E. H., Thompson, J., Hill, S. R., Williams, M., Paton, D., Harrison, S. E., Bostrom, A., & Becker, J. S. (2024). Differences in perceived sources of uncertainty in natural hazards science advice: Lessons for cross-disciplinary communication. *Frontiers in Communication, 9*. <https://doi.org/10.3389/fcomm.2024.1366995>

Williams, M. N., Ling, M., Kerr, J. R., Hill, S. R., Marques, M. D., Mawson, H., & Clarke, E. J. R. (2024). People do change their beliefs about conspiracy theories—but not often. *Scientific Reports, 14*, 3836. <https://doi.org/10.1038/s41598-024-51653-z>

Garea, S. S., Sauer, J. D., Hall, L. C., Williams, M. N., & Drummond, A. (2023). The potential relationship between loot box spending, problem gambling, and obsessive-compulsive gamers. *Journal of Behavioral Addictions, 12*(3), 733-743. <https://doi.org/10.1556/2006.2023.00038>

Doyle, E. E. H., Thompson, J., Hill, S. R., Williams, M. N., Paton, D., Harrison, S., Borstom, A., & Becker, J. (2023). Where does scientific uncertainty come from, and from whom? Mapping perspectives of natural hazards science advice. *International Journal of Disaster Risk Reduction, 96*(1), 103948. <https://doi.org/10.1016/j.ijdrr.2023.103948>

Henry, N., Pederson, M., Williams, M. N., & Donkin, L. (2023). Behavioral posology: A novel paradigm for modeling the healthy limits of behaviors. *Advanced Theory and Simulations, 6*(9), 2300214. <https://doi.org/10.1002/adts.202300214>

Faulkner, J., Theadom, A., Snell, D., & Williams, M. N. (2023). Network analysis applied to post-concussion symptoms in two mild traumatic brain injury samples. *Frontiers in Neurology, 14*. <https://doi.org/10.3389/fneur.2023.1226367>

Valdes, E. A., Liu, J. H., & Williams, M. N. (2022). Testing the status-legitimacy hypothesis: Predicting system justification using objective and subjective socioeconomic status in China and the United States. *Asian Journal of Social Psychology, 26*(2), 238-253. <https://doi.org/10.1111/ajsp.12555>

Gibson, C., Williams, M. N., Ross, K., & de Vries, N. (2023). Distress, self-efficacy, feeling informed and the Babble app: A New Zealand neonatal parent sample. *Journal of Neonatal Nursing, 29*(2), 273-277. <https://doi.org/10.1016/j.jnn.2022.06.004>  Preprint: <https://doi.org/10.31234/osf.io/nguk8>

Henry, N., Donkin, L., Williams, M. N., & Pedersen, M. (2022). m-Health technologies for managing problematic pornography use: A literature review and content analysis of current apps. *JMIR Formative Research*. <https://doi.org/10.2196/39869>

Williams, M. N., Marques, M. D., Hill, S. R., Kerr, J. R., & Ling, M. (2022). Why are beliefs in different conspiracy theories positively correlated across individuals? Testing monological network versus unidimensional factor model explanations \[Registered Report\]. *British Journal of Social Psychology, 61*(3), 1011-1031. <https://doi.org/10.1111/bjso.12518>  Stage 1 manuscript, data, code, materials: <https://osf.io/y3rfz/>

Hudson-Doyle, E. H., Harrison, S. E., Hill, S. R., Williams, M. N., Paton, D., & Bostrom, A. (2022). Eliciting mental models of science and risk for disaster communication: A scoping review of methodologies. *International Journal of Disaster Risk Reduction, 77*(103084). <https://doi.org/10.1016/j.ijdrr.2022.103084>

Dodge, A., Gibson, C. M. B., Williams, M. N., & Ross, K. (2022). Exploring the needs and coping strategies of New Zealand parents in the neonatal environment. *Journal of Paediatrics and Child Health, 58*(6), 1060-1065. <https://doi.org/10.1111/jpc.15908>

Williams, M. N., & Hill, S. R. (2022). Inferences about the effect of lockdowns on mental health require causal identification strategies: A reply to Thornley et al. \[Letter to the editor\]. *Journal of Paediatrics and Child Health, 58*(1), 216-217. <https://doi.org/10.1111/jpc.15853> Preprint: <https://doi.org/10.31234/osf.io/u7jfa>

Feather, G., & Williams, M. N. (2022). The moderating effects of psychological flexibility and psychological inflexibility on the relationship between climate concern and climate-related distress. *Journal of Contextual Behavioral Science, 23*, 137-143. <https://doi.org/10.1016/j.jcbs.2021.12.007>

Marques, M., Hill, S. R., Clarke, E. J. R., Williams, M. N., Ling, M., Kerr, J. R., Douglas, K. M., Cichocka, A., & Sibley, C. G. (2022). Democracy and belief in conspiracy theories in New Zealand. *Australian Journal of Political Science, 57*(3), 264-279. <https://doi.org/10.1080/10361146.2022.2122773> Postprint: <https://doi.org/10.31234/osf.io/s8qf4>

Williams, M. N., & Marshall-Edwards, S. (2022). Conceptual replication of Seo (2008), “Self-efficacy as a mediator in the relationship between self-oriented perfectionism and academic procrastination”. *Current Issues in Personality Psychology, 10*(2). <https://doi.org/10.5114/cipp.2021.110948>

Holman, M., & Williams, M. N. (2022). Suicide risk and protective factors: A network approach. *Archives of Suicide Research, 26*(1), 137-154. <https://doi.org/10.1080/13811118.2020.1774454> Preprint: <https://doi.org/10.31234/osf.io/rf4ej>

Smith, J. H., Kempton, H. M., Williams, M. N., & van Ommen, C. (2021). Mindfulness as practice: A network analysis of FMI data. *Counselling and Psychotherapy Research, 21*(4), 899-909. <https://doi.org/10.1002/capr.12400> Postprint: <https://doi.org/10.31234/osf.io/4rymb>

Marques, M. D., Kerr, J., Williams, M. N., Ling, M., & McLennan, J. (2021). Associations between conspiracism and the rejection of scientific innovations. *Public Understanding of Science, 30*(7), 854-867. <https://doi.org/10.1177/09636625211007013> Preprint: <https://doi.org/10.31234/osf.io/y9mnb>

Brown, N. J. L., van Rongen, J. B., van der Velde, J., & Williams, M. N. (2021). A reproduction of the results of Onyike et al. (2003). *Meta-Psychology, 5*. <https://doi.org/10.15626/MP.2019.2071>

Williams, M. N. (2021). Levels of measurement and statistical analyses. *MetaPsychology*. <https://doi.org/10.15626/MP.2019.1916>

Garea, S. S., Drummond, A., Sauer, J. D., Hall, L. C., & Williams, M. N. (2021). Meta-analysis of the relationship between problem gambling, excessive gaming and loot box spending. *International Gambling Studies, 21*(3), 460-479. <https://doi.org/10.1080/14459795.2021.1914705> Preprint: <https://doi.org/10.31234/osf.io/ug4jy>

Marques, M. D, Ling, M., Williams, M. N., Kerr, J., & McLennan, J. (2022). Australasian public awareness and belief in conspiracy theories: Motivational correlates. *Political Psychology, 43*(1), 177-198. <https://doi.org/10.1111/pops.12746>  Preprint: <https://doi.org/10.31234/osf.io/vr896>

Gibson, C., Ross, K., Williams, M. N., & de Vries, N. (2021). The experiences of mothers in a neonatal unit and their use of the Babble app. *SAGE Open*. <https://doi.org/10.1177/21582440211023170>

Kember, S., & Williams, M. N. (2021). Autism in Aotearoa: is the RAADS-14 a valid tool for a New Zealand population? \[Registered Report\] *European Journal of Psychological Assessment, 37*(3), 247-257. <https://doi.org/10.1027/1015-5759/a000598> Stage 1, data, code: <https://osf.io/4szdg/> Postprint: <https://mro.massey.ac.nz/handle/10179/15518>

Williams, M. N., & Bond, C. M. C. (2020). A preregistered replication of “Inoculating the public against misinformation about climate change”. *Journal of Environmental Psychology, 70*, 101456. <https://doi.org/10.1016/j.jenvp.2020.101456> Postprint: <https://doi.org/10.31234/osf.io/hqme7>

Scott-Campbell, C. A., & Williams, M. N. (2020). Validating the workplace dignity scale. *Collabra: Psychology, 6*(1), 31. <http://doi.org/10.1525/collabra.337>

Williams, M. N., & Jaftha, B. A. (2020). Perceptions of powerlessness are negatively associated with taking action on climate change: A Preregistered Replication. *Ecopsychology, 12*(4), 257-266. <https://doi.org/10.1089/eco.2020.0012> Postprint: <https://doi.org/10.31234/osf.io/ers4v>

Holman, M., & Williams, M. N. (2020). Young New Zealanders' beliefs about youth suicide and how it can be prevented. *New Zealand Journal of Psychology, 49*(1), 22-28. <https://www.psychology.org.nz/application/files/7615/9538/4266/Holman_and_Williams_22-28.pdf>

Williams, M. N., & Albers, C. (2019). Dealing with distributional assumptions in preregistered research. *Meta-Psychology, 3*. <https://doi.org/10.15626/MP.2018.1592>

O’Donnell, M., Nelson, L. D., Ackermann, E., Aczel, B., Akhtar, A., Aldrovandi, S., … Williams, M. N., … Zrubka, M. (2018; 118 authors). Registered replication report: Dijksterhuis & van Knippenberg (1998). *Perspectives on Psychological Science, 13*(2), 268-294. <https://doi.org/10.1177%2F1745691618755704>

Lakens, D., Adolfi, F. G., Albers, C. J., Anvari, F., Apps, M. A. J., Argamon S, E., … Williams, M. N., … Zwaan, R. A. (2018; 87 authors). Justify your alpha: A response to “Redefine Statistical Significance”. *Nature Human Behaviour, 2*, 168-171. <https://doi.org/10.1038/s41562-018-0311-x>

Williams, M. N., Bååth, R. A., & Philipp, M. C. (2017). Using Bayes factors to test hypotheses in developmental research. *Research in Human Development, 14*(4), 321–337. <https://doi.org/10.1080/15427609.2017.1370964>

Furness, K., Williams, M. N., Veale, J. F., & Gardner, D. H. (2017). Maximizing potential: The effects of Project K on self-efficacy, resilience, and connectedness. *New Zealand Journal of Psychology, 46*(1), 14-23. <https://www.psychology.org.nz/journal-archive/The-Psychological-Effects-of-the-Youth-Development-Programme-Project-K.pdf>

Veale, J. F., & Williams, M. N. (2017). The psychometric properties of a brief version of the Systemizing Quotient. *European Journal of Psychological Assessment, 33*(3), 173–180. <https://doi.org/10.1027/1015-5759/a000283>

Towers, A., Williams, M. N., Hill, S. R., Philipp, M. C., & Flett, R. (2016). What makes for the most intense regrets? Comparing the effects of several theoretical predictors of regret intensity. *Frontiers in Psychology, 7*. <https://doi.org/10.3389/fpsyg.2016.01941>

Williams, M. N., Hill, S. R., & Spicer, J. (2015). The relationship between temperature and assault in New Zealand. *Climatic Change, 132*(4), 559–573. <https://doi.org/10.1007/s10584-015-1438-7>  Postprint: <https://doi.org/10.31234/osf.io/sufkj>

Williams, M. N., Hill, S. R., & Spicer, J. (2015). Will climate change increase or decrease suicide rates? The differing effects of geographical, seasonal, and irregular variation in temperature on suicide incidence. *Climatic Change, 130*(4), 519–528. <https://doi.org/10.1007/s10584-015-1371-9> Postprint: <https://doi.org/10.31234/osf.io/cbzn9>

Williams, M. N., Hill, S. R., & Spicer, J. (2015). Do hotter temperatures increase the incidence of self-harm hospitalisations? *Psychology, Health and Medicine, 21*(2), 226–235. <https://doi.org/10.1080/13548506.2015.1028945> Postprint: <https://doi.org/10.31234/osf.io/cp5dm>

Williams, M. N., Hill, S. R., & Spicer, J. (2013). In response to ‘Temperature and violent crime in Dallas, Texas: Relationships and implications of climate change’. *Western Journal of Emergency Medicine, 14*(5), 567–568. <https://doi.org/10.5811/westjem.2013.5.17833>

Williams, M. N., Grajales, C. A. G., & Kurkiewicz, D. (2013). Assumptions of multiple regression: correcting two misconceptions. *Practical Assessment, Research & Evaluation, 18*. <https://doi.org/10.7275/55hn-wk47>

Williams, M. N., & Jones, L. M. (2012). Validating a measure of children’s monitoring-blunting coping styles in dental situations. *Psychology, Health & Medicine, 17*, 274–284. <https://doi.org/10.1080/13548506.2011.601748> Postprint: <https://mro.massey.ac.nz/handle/10179/9467>

Williams, M. W. M., & Williams, M. N. (2012). Academic dishonesty, self-control and general criminality: A prospective and retrospective study of academic dishonesty in a New Zealand university. *Ethics & Behavior, 22*(2), 89–112. <https://doi.org/10.1080/10508422.2011.653291> Postprint: <https://mro.massey.ac.nz/handle/10179/9466>

## Preprints

Williams, M. N., Marques, M. D., Ling, M., Hill, S. R., Kerr, J. R., Clarke, E. J. R., Martin, A., & Ross, R. M. (2026). Do you really believe that? Examining the prevalence and predictors of belief in conspiracy theories when accounting for insincerity \[Stage 2 Registered Report\]. <https://doi.org/10.31234/osf.io/9ntf2_v1> PCI RR recommendation: <https://rr.peercommunityin.org/PCIRegisteredReports/articles/rec?id=1201>

Damnjanovic, N., Williams, M. N., & Ross, K. (2023). The “ACT-ive” pursuit of loss and gain: The impact of an Acceptance and Commitment Therapy-based intervention on post weight-loss surgery individuals. *PsyArXiv*. <https://doi.org/10.31234/osf.io/5mbeq>

van Beynen, J., & Williams, M. N. (2023). Communicating the scientific consensus on climate change: A preregistered test of the gateway belief model with a one-week time delay. *PsyArXiv*. <https://doi.org/10.31234/osf.io/f3svr>

Williams, M. N., Anderson, R. C., Fox, N., Skinner, C. M., & McMurtrie, B. (2022). Evidence for a positive relationship between perceived stress and belief in conspiracy theories. *PsyArXiv*. <https://doi.org/10.31234/osf.io/gca56>

Williams, M. N., & Gill, C. M. (2020). Preregistered replication of Stoeber (2012): Dyadic perfectionism in romantic relationships. *PsyArXiv*. <https://doi.org/10.31234/osf.io/2br58>

## Theses

Williams, M. N. (2015). How well do psychologists' research methods equip them to identify the impacts of climate change on behaviour? A methodological investigation with particular reference to the effects of temperature on violent behaviour (PhD thesis). Massey University, Auckland, New Zealand. <https://mro.massey.ac.nz/handle/10179/8282>

Williams, M. N. (2010). Coping in the chair: A validation study of the Monitoring Blunting Dental Scale (Master’s thesis). Massey University, Wellington, New Zealand. <https://mro.massey.ac.nz/handle/10179/1537>
